### ISSUE TITLE
Not use fixed list of audio source types

### ISSUE THREAD

**Issue by exeldro** [nuttylmao/NOOBS-CMDR#1]
https://github.com/nuttylmao/NOOBS-CMDR/blob/6e96bb37d131e30033beae55c8afd9eab61729fe/Controls/Commands/AudioControl.xaml.cs#L83

Instead of a fixed list of audio source types you can check Capabilities.HasAudio from GetSourceTypesList()
That way other sources from other plugins also work.

**Comment by nuttylmao** [comment]
Awesome, thanks for the info. Will fix before Monday's stream.
