### ISSUE TITLE
WARNING: The data being saved is truncated to 1024 characters.

### ISSUE THREAD

**Issue by bvharen** [nuttylmao/NOOBS-CMDR#3]
`setx /m PATH "%PATH%%~dp0OBSCommand"
pause`

WARNING: The data being saved is truncated to 1024 characters.

After added it manual it worked ^^

**Comment by nuttylmao** [comment]
Created a new Installer. You don't need to add a path anymore, so you can remove it. New installer will just copy OBSCommand to your System32 directory.
