### ISSUE TITLE
In the Chinese environment, the exported bat will not work correctly due to encoding issues

### ISSUE THREAD

**Issue by Danjuanlab** [nuttylmao/NOOBS-CMDR#5]
When the scene or filter name of OBS contains Chinese, although the correct scene name will be included in the bat exported by noobs, the script cannot be executed because the Chinese name is garbled when the bat is executed. I think this will also happen in a non-English environment, not just a Chinese encoding issue.
When I add chcp 65001 to the script, the script can be used normally.
![捕获](https://user-images.githubusercontent.com/42509669/104113284-e0ce0380-5332-11eb-9b61-181d6b40b7a5.PNG)

**Comment by nuttylmao** [comment]
Thanks, you're right! I've fixed both .bat and .vbs exports. You will need to re-export with the newest release.
